class AuthenticationError(Exception):
    pass

class ValidationError(Exception):
    pass